### Hyperparameters for the G2-structure learning runs ###

###############################################################################
# Geometric set-up
# Dimensionality of the data (e.g., 2 for 2D data)
dim: 7

# Set the number of patches (current functionality for 1 or 2)
n_patches: 1 ###need patch_change funcs before make 5

# Patching size
# ...determines the distance from the radial midpoint to the outer edge of the 
# overlap region within the patches
overlap_upperwidth: 0.1 

###############################################################################
# Data set-up
# Number of samples to generate for training
num_samples: 10000

###############################################################################
# Model set-up
# Import a saved model instead of initiating a new one (null means randomly initialise)
saved_model: false
saved_model_path: ...
# ...the below are ignored if `saved_model` is true and a model is imported

# Number of hidden units in each layer
n_hidden: 64

# Number of layers in the neural network
n_layers: 3

# Activation function to use in the neural network (e.g., gelu, relu)
activations: gelu

# Whether to use bias terms in the neural network layers
use_bias: true

###############################################################################
# Training set-up
# Number of training epochs
epochs: 100

# Batch size for training
batch_size: 100

# Learning rate for the optimizer
init_learning_rate: 0.005
min_learning_rate: 0.005

# Validation hyperparameters
validate: false
val_print: false
num_val_samples: 2000
val_batch_size: 100

# Verbosity level for print logging (e.g., 0 for silent, 1 for progress messages)
verbosity: 1

###############################################################################
#Logging set-up
###where to save the models too

# Whether to print a breakdown of individual loss terms with each training step
print_losses: false
print_interval: 1   